version: '3.0'

services:
  web:
    build: .
    links:
      - db
    user: "1001:1001"
    ports:
      - "8080:8080"
    environment:
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_NAME: matomo
      MATOMO_DATABASE_USER: root
      MATOMO_DATABASE_PASSWORD: my-secret-pw
      MATOMO_SALT: testsalt
      MATOMO_TRUSTED_HOSTS: "localhost:8080"

  db:
    image: "mariadb:10.11.3-jammy"
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
